[global]
server_name = "localhost:6167"
database_path = "/srv/conduit/.local/share/conduit"
port = 6167
max_request_size = 20_000_000 # in bytes
allow_registration = true
allow_federation = false
trusted_servers = ["matrix.org"]
log = "warn,state_res=warn,rocket=off,_=off,sled=off"
workers = 4 # default: cpu core count * 2
address = "0.0.0.0" # This makes sure Conduit can only be reached using the reverse proxy

