name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:


  test:
    name: ${{ matrix.name }}
    #needs: [clippy]

    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      matrix:
        name:
          - linux / stable
          #- linux / beta
          #- macOS / stable

        include:
          - name: linux / stable

          #- name: linux / beta
          #  rust: beta
          #
          #- name: macOS / stable
          #  os: macOS-latest
    
    services:
      conduit:
        image: matrixconduit/matrix-conduit:latest
        ports:
          - 6167:6167
        volumes:
          - db:/srv/conduit/.local/share/conduit
        env:
          CONDUIT_SERVER_NAME: localhost:6167
          CONDUIT_ALLOW_REGISTRATION: true
          CONDUIT_ADDRESS: 0.0.0.0
          CONDUIT_PORT: 6167
          CONDUIT_LOG: warn
          CONDUIT_ALLOW_FEDERATION: false
          CONDUIT_DATABASE_PATH: /srv/conduit/.local/share/conduit
        options: >-
          # Workaround to be able to set an env var to an empty string in GH actions
          -e "CONDUIT_CONFIG=''"
    steps:


      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust || 'stable' }}
          target: ${{ matrix.target }}
          profile: minimal
          override: true

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
